project:
  type: website
  output-dir: _site

website:
  title: "Dr. Jayaruwani Fernando - Research & Scholarship"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme: flatly
    css: styles.css
